"""Audit trail foundation for the runner.

Adım 12 PR-2b2a (reporting refactor plan §400 — audit trail foundation).
This module owns only the **event vocabulary** + **JSON Lines
writer**. Checkpoint/resume semantics and reports_db idempotency are
deliberately out of scope (Codex `019e2a5c` discipline: this is
"audit trail foundation", not "audit/resume").

Design contract:

* **JSON Lines (``.jsonl``)** — one event per line, append-only,
  grep + tail friendly.
* **Stable schema** — every event carries ``schema_version``,
  ``timestamp`` (ISO 8601 UTC, ms precision), ``run_id`` (caller
  override or autogenerated ``uuid.uuid4().hex``), ``event`` name,
  ``attempt`` (or ``null`` for run-level), ``outcome``, ``summary``
  (or ``null``), ``error_class``, ``error_message`` (sanitized, max
  500 chars).
* **Bounded error payload** — the error message is *truncated* (not
  redacted) at :data:`MAX_ERROR_MESSAGE_LENGTH` so an oversize
  upstream string cannot bloat a log line or leak surprise content.
  Active secret redaction is out of scope for this slice; callers
  control what they pass via ``error_message``.
* **No fsync per event** — line-buffered append is enough for
  operator log analysis. Durability knobs (``--fsync-audit``) belong
  to a later slice if/when operator workflow demands it.

The writer is fronted by an :class:`AuditWriter` Protocol so future
PRs (and tests) can swap in alternative backends (in-memory,
network sink) without touching the runner.
"""

from __future__ import annotations

import json
import os
import threading
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Protocol

SCHEMA_VERSION = 1
"""Audit event schema version. Bump when fields change incompatibly."""

MAX_ERROR_MESSAGE_LENGTH = 500
"""Cap on ``error_message`` payload to bound accidental leakage."""


@dataclass(frozen=True, slots=True)
class AuditEvent:
    """One audit trail entry.

    Frozen dataclass so the writer cannot mutate the payload after
    construction. ``run_id`` is propagated by the caller; the writer
    is purely a sink.

    Field semantics:

    * ``event`` — vocabulary: ``"run_started"`` / ``"attempt_started"``
      / ``"attempt_succeeded"`` / ``"attempt_failed"`` /
      ``"run_succeeded"`` / ``"run_failed"``.
    * ``attempt`` — 1-indexed; ``None`` for ``run_started`` /
      ``run_succeeded`` / ``run_failed`` events that are not tied to
      a specific attempt.
    * ``outcome`` — short descriptor: ``"success"`` /
      ``"retryable_failure"`` / ``"terminal_failure"`` /
      ``"contract_drift"`` etc. Free-form within a small enum the
      runner controls.
    * ``summary`` — only set on ``run_succeeded``; mirrors the PR-2a
      / PR-2b1 stdout JSON shape so the audit log carries the same
      contract.
    * ``error_class`` / ``error_message`` — only set on failure
      events; ``error_message`` is truncated by the writer to
      :data:`MAX_ERROR_MESSAGE_LENGTH`.
    """

    schema_version: int
    timestamp: str
    run_id: str
    event: str
    attempt: int | None = None
    outcome: str | None = None
    summary: dict[str, object] | None = None
    error_class: str | None = None
    error_message: str | None = None
    extra: dict[str, object] = field(default_factory=dict)


class AuditWriter(Protocol):
    """Sink interface used by :func:`etl_worker.runner.run_fetch`."""

    def write(self, event: AuditEvent) -> None:  # pragma: no cover - Protocol
        ...


class JsonLinesAuditWriter:
    """Append :class:`AuditEvent` records as JSON Lines to a file path.

    Each :meth:`write` performs **one** ``write(2)`` system call on a
    handle opened with ``O_APPEND``; this is the strongest single-
    process atomicity guarantee POSIX makes for regular files. The
    JSON payload + trailing newline are pre-encoded as a single bytes
    object so the line cannot be split across system calls.

    .. note::
       The traditional ``PIPE_BUF`` (4 KiB) atomicity rule applies to
       pipes / FIFOs only, **not** regular files. Cross-process
       guarantees on regular files vary by filesystem (local ext4 /
       APFS are well-behaved; NFS and other network filesystems are
       not promised). We therefore do not claim cross-process line
       atomicity here — the writer is designed for the single-process
       runner today, with the threading lock below covering
       in-process concurrency.

    Threading:
        Within a single process, an internal :class:`threading.Lock`
        serialises writes so concurrent emissions from the runner +
        future async retry / DB writer slices stay line-coherent.
    """

    def __init__(self, path: str | os.PathLike[str]) -> None:
        self._path = Path(path)
        self._lock = threading.Lock()
        # Eagerly ensure the parent directory exists so the first
        # ``write()`` does not fail in a containerised job where the
        # mount path is created late by the orchestrator.
        self._path.parent.mkdir(parents=True, exist_ok=True)

    @property
    def path(self) -> Path:
        return self._path

    def write(self, event: AuditEvent) -> None:
        payload = self._payload(event)
        line = json.dumps(payload, separators=(",", ":"), sort_keys=True)
        # Encode the JSON line + trailing newline as a single bytes
        # buffer so a single ``write(2)`` system call emits the whole
        # record. Splitting JSON and ``"\n"`` across two ``handle.write``
        # calls (the previous implementation) created a tiny window
        # where an interleaving in-process or cross-process writer
        # could corrupt line framing.
        encoded = (line + "\n").encode("utf-8")
        with self._lock:
            fd = os.open(
                self._path,
                os.O_WRONLY | os.O_CREAT | os.O_APPEND,
                0o644,
            )
            try:
                os.write(fd, encoded)
            finally:
                os.close(fd)

    def _payload(self, event: AuditEvent) -> dict[str, object]:
        data: dict[str, object] = {
            key: value
            for key, value in asdict(event).items()
            if value is not None and key != "extra"
        }
        # Always carry ``extra`` if non-empty so callers can attach
        # diagnostics without growing the dataclass surface.
        if event.extra:
            data["extra"] = dict(event.extra)
        if event.error_message is not None:
            data["error_message"] = _truncate_error(event.error_message)
        return data


def _truncate_error(message: str) -> str:
    """Bound the ``error_message`` payload.

    Keeps audit lines small + reduces accidental leakage if an
    upstream error string ever includes more than intended.
    """
    if len(message) <= MAX_ERROR_MESSAGE_LENGTH:
        return message
    return message[: MAX_ERROR_MESSAGE_LENGTH - 1] + "…"


def now_isoformat() -> str:
    """Current timestamp in ISO 8601 UTC with millisecond precision.

    Centralised so tests can monkeypatch a single name when they need
    deterministic timestamps in audit assertions.
    """
    now = datetime.now(UTC)
    # ``isoformat(timespec="milliseconds")`` produces e.g.
    # ``2026-05-15T08:31:37.123+00:00``; rewrite the tz offset to ``Z``
    # for compactness in the audit file (operators prefer ``Z``).
    return now.isoformat(timespec="milliseconds").replace("+00:00", "Z")


def build_event(
    *,
    run_id: str,
    event: str,
    attempt: int | None = None,
    outcome: str | None = None,
    summary: dict[str, object] | None = None,
    error_class: str | None = None,
    error_message: str | None = None,
    extra: dict[str, object] | None = None,
) -> AuditEvent:
    """Helper that fills :attr:`AuditEvent.schema_version` /
    :attr:`AuditEvent.timestamp` so callers do not duplicate those
    fields at every emission site."""
    return AuditEvent(
        schema_version=SCHEMA_VERSION,
        timestamp=now_isoformat(),
        run_id=run_id,
        event=event,
        attempt=attempt,
        outcome=outcome,
        summary=summary,
        error_class=error_class,
        error_message=error_message,
        extra=dict(extra) if extra else {},
    )
