-- Faz 35 ES-207 — durable audit outbox delivery and product-local WORM ledger.
--
-- The business mutation and ethics_audit_outbox INSERT already share one
-- transaction. This migration adds a leased delivery lifecycle and a separate,
-- append-only, hash-chained sink. Provider/sink outage never rolls back the
-- original report/message/case commit; it leaves a visible retryable row.

ALTER TABLE ethics_audit_outbox
    ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ethics_audit_outbox
    ADD COLUMN next_attempt_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE ethics_audit_outbox
    ADD COLUMN claim_token UUID;
ALTER TABLE ethics_audit_outbox
    ADD COLUMN locked_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE ethics_audit_outbox
    ADD COLUMN delivered_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE ethics_audit_outbox
    ADD COLUMN last_error_code VARCHAR(120);

ALTER TABLE ethics_audit_outbox
    ADD CONSTRAINT ck_ethics_audit_outbox_status
    CHECK (status IN ('PENDING', 'PROCESSING', 'DELIVERED', 'DEAD_LETTER'));

CREATE INDEX ix_ethics_audit_delivery_due
    ON ethics_audit_outbox(status, next_attempt_at, created_at);
CREATE INDEX ix_ethics_audit_claim_token
    ON ethics_audit_outbox(claim_token);

CREATE TABLE ethics_worm_audit (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id UUID NOT NULL UNIQUE,
    source_outbox_id UUID NOT NULL UNIQUE REFERENCES ethics_audit_outbox(id),
    org_id UUID NOT NULL,
    aggregate_id UUID NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    payload VARCHAR(4000) NOT NULL,
    event_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ingested_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    prev_hash VARCHAR(64),
    entry_hash VARCHAR(64) NOT NULL,
    entry_hash_alg VARCHAR(32) NOT NULL,
    entry_hash_version INTEGER NOT NULL,
    CONSTRAINT ck_ethics_worm_entry_hash
        CHECK (CHAR_LENGTH(entry_hash) = 64),
    CONSTRAINT ck_ethics_worm_prev_hash
        CHECK (prev_hash IS NULL OR CHAR_LENGTH(prev_hash) = 64),
    CONSTRAINT ck_ethics_worm_hash_version
        CHECK (entry_hash_version = 1)
);

CREATE INDEX ix_ethics_worm_org_seq
    ON ethics_worm_audit(org_id, seq DESC);
CREATE INDEX ix_ethics_worm_event_time
    ON ethics_worm_audit(org_id, event_timestamp);

-- Application repositories expose INSERT/read only. PostgreSQL adds the hard
-- UPDATE/DELETE rejection trigger in the vendor-specific V4 migration.
