-- Faz 35 ES-104 — attachment quarantine and dual-artifact custody.
--
-- The row contains only bounded operational metadata and opaque object keys.
-- Original filenames, evidence bytes, extracted text, reporter identity,
-- receipts, mailbox secrets and storage credentials are deliberately absent.

CREATE TABLE ethics_evidence_attachments (
    id UUID PRIMARY KEY,
    case_id UUID NOT NULL REFERENCES ethics_cases(id),
    org_id UUID NOT NULL,
    channel VARCHAR(80) NOT NULL,
    state VARCHAR(40) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    policy_version VARCHAR(80) NOT NULL,
    declared_media_type VARCHAR(80) NOT NULL,
    declared_size BIGINT NOT NULL,
    declared_sha256 VARCHAR(64) NOT NULL,
    quarantine_key VARCHAR(160) NOT NULL UNIQUE,
    sealed_key VARCHAR(160) NOT NULL UNIQUE,
    derivative_key VARCHAR(160) NOT NULL UNIQUE,
    upload_capability_hash VARCHAR(64) NOT NULL UNIQUE,
    upload_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    upload_consumed_at TIMESTAMP WITH TIME ZONE,
    sealed_version_id VARCHAR(240),
    sealed_sha256 VARCHAR(64),
    sealed_size BIGINT,
    derivative_version_id VARCHAR(240),
    derivative_sha256 VARCHAR(64),
    derivative_size BIGINT,
    derivative_media_type VARCHAR(80),
    failure_code VARCHAR(120),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE,
    claim_token UUID,
    locked_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_ethics_evidence_idempotency
        UNIQUE(case_id, idempotency_key),
    CONSTRAINT ck_ethics_evidence_state CHECK (state IN (
        'DECLARED','UPLOADING','QUARANTINED','INTEGRITY_VERIFIED',
        'ORIGINAL_SEALED','SCANNING','SANITIZING','DERIVATIVE_READY',
        'AVAILABLE','REJECTED_INTEGRITY','REJECTED_POLICY',
        'MALICIOUS_QUARANTINED','SCAN_PENDING','SANITIZE_FAILED',
        'EXPIRED_UNBOUND','DISPOSED')),
    CONSTRAINT ck_ethics_evidence_size
        CHECK (declared_size > 0 AND declared_size <= 26214400),
    CONSTRAINT ck_ethics_evidence_declared_sha
        CHECK (CHAR_LENGTH(declared_sha256) = 64),
    CONSTRAINT ck_ethics_evidence_request_hash
        CHECK (CHAR_LENGTH(request_hash) = 64),
    CONSTRAINT ck_ethics_evidence_capability_hash
        CHECK (CHAR_LENGTH(upload_capability_hash) = 64),
    CONSTRAINT ck_ethics_evidence_sealed_sha
        CHECK (sealed_sha256 IS NULL OR CHAR_LENGTH(sealed_sha256) = 64),
    CONSTRAINT ck_ethics_evidence_derivative_sha
        CHECK (derivative_sha256 IS NULL OR CHAR_LENGTH(derivative_sha256) = 64)
);

CREATE INDEX ix_ethics_evidence_case_time
    ON ethics_evidence_attachments(case_id, created_at);
CREATE INDEX ix_ethics_evidence_pipeline_due
    ON ethics_evidence_attachments(state, next_attempt_at, created_at);
CREATE INDEX ix_ethics_evidence_claim
    ON ethics_evidence_attachments(claim_token);

CREATE TABLE ethics_evidence_derivations (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id UUID NOT NULL UNIQUE,
    attachment_id UUID NOT NULL REFERENCES ethics_evidence_attachments(id),
    derivation_version INTEGER NOT NULL,
    sealed_sha256 VARCHAR(64) NOT NULL,
    sealed_size BIGINT NOT NULL,
    derivative_sha256 VARCHAR(64) NOT NULL,
    derivative_size BIGINT NOT NULL,
    input_media_type VARCHAR(80) NOT NULL,
    output_media_type VARCHAR(80) NOT NULL,
    scanner_digest VARCHAR(120) NOT NULL,
    sanitizer_digest VARCHAR(120) NOT NULL,
    parser_digest VARCHAR(120) NOT NULL,
    rules_version VARCHAR(120) NOT NULL,
    policy_version VARCHAR(80) NOT NULL,
    transformation_profile VARCHAR(120) NOT NULL,
    previous_manifest_hash VARCHAR(64),
    manifest_hash VARCHAR(64) NOT NULL,
    signature_alg VARCHAR(40) NOT NULL,
    manifest_signature VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_ethics_evidence_derivation_version
        UNIQUE(attachment_id, derivation_version),
    CONSTRAINT ck_ethics_evidence_derivation_hashes CHECK (
        CHAR_LENGTH(sealed_sha256) = 64
        AND CHAR_LENGTH(derivative_sha256) = 64
        AND CHAR_LENGTH(manifest_hash) = 64
        AND (previous_manifest_hash IS NULL OR CHAR_LENGTH(previous_manifest_hash) = 64)),
    CONSTRAINT ck_ethics_evidence_signature_alg
        CHECK (signature_alg = 'HMAC-SHA256')
);

CREATE INDEX ix_ethics_evidence_derivation_attachment
    ON ethics_evidence_derivations(attachment_id, derivation_version DESC);
