package com.example.permission.service;

import com.example.permission.model.ImpersonationSession;
import com.example.permission.repository.ImpersonationSessionRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

/**
 * User Impersonation v1 — Authoritative session service (permission-service).
 *
 * <p>Codex 019e0dfb iter-26 mimari split:
 * <ul>
 *   <li>auth-service = identity broker (KC token exchange, public endpoint)</li>
 *   <li>permission-service = session/audit authority (internal API, DB write)</li>
 * </ul>
 *
 * <p>auth-service permission DB'ye doğrudan yazmaz; bu service üzerinden
 * internal session create/stop yapar.
 */
@Service
public class ImpersonationSessionService {

    private static final Logger log = LoggerFactory.getLogger(ImpersonationSessionService.class);

    private final ImpersonationSessionRepository sessionRepository;

    public ImpersonationSessionService(ImpersonationSessionRepository sessionRepository) {
        this.sessionRepository = sessionRepository;
    }

    /**
     * Start a new impersonation session.
     *
     * <p>Codex iter-25/26 absorb:
     * <ul>
     *   <li>Sweep expired sessions ÖNCE (partial unique index race önleme)</li>
     *   <li>Same transaction'da insert</li>
     *   <li>{@link DataIntegrityViolationException} → {@link ActiveSessionExistsException}
     *       (single-active-session policy 409 mapping)</li>
     * </ul>
     *
     * @return persisted session row (id generated by entity @PrePersist)
     * @throws ActiveSessionExistsException if impersonator already has an
     *         active session (DB unique violation).
     */
    @Transactional
    public ImpersonationSession startSession(StartSessionRequest request) {
        Instant now = Instant.now();

        // Step 1: sweep expired-but-still-ACTIVE sessions (race önleme)
        int swept = sessionRepository.sweepExpiredSessions(now);
        if (swept > 0) {
            log.debug("Swept {} expired session(s) before start", swept);
        }

        // Step 2: build entity (id @PrePersist ile JVM-side)
        ImpersonationSession session = new ImpersonationSession();
        session.setImpersonatorUserId(request.impersonatorUserId());
        session.setImpersonatorSubject(request.impersonatorSubject());
        session.setImpersonatorEmail(request.impersonatorEmail());
        session.setTargetUserId(request.targetUserId());
        session.setTargetSubject(request.targetSubject());
        session.setTargetEmail(request.targetEmail());
        session.setIssuer(request.issuer());
        session.setJti(request.jti());
        session.setSid(request.sid());
        session.setReason(request.reason());
        session.setStartedAt(now);
        session.setExpiresAt(request.expiresAt());
        session.setStatus(ImpersonationSession.Status.ACTIVE);
        session.setIpAddress(request.ipAddress());
        session.setUserAgent(request.userAgent());
        session.setClientIpViaXff(request.clientIpViaXff());

        // Step 3: insert (DB unique constraint çakışırsa 409)
        try {
            ImpersonationSession saved = sessionRepository.save(session);
            log.info("Impersonation session started: id={} impersonator={} target={}",
                    saved.getId(), saved.getImpersonatorUserId(), saved.getTargetUserId());
            return saved;
        } catch (DataIntegrityViolationException e) {
            // Codex iter-27 P1 absorb: constraint name'ine göre ayrıştır.
            // ux_impersonation_sessions_one_active_per_impersonator violation
            // → ActiveSessionExistsException (409). Diğer constraint
            // (no_self, expires_after_start, status_check) → 400 BadRequest.
            String message = e.getMessage() != null ? e.getMessage().toLowerCase() : "";
            if (message.contains("ux_impersonation_sessions_one_active_per_impersonator")) {
                log.warn("Active impersonation session already exists for impersonator={}",
                        request.impersonatorUserId());
                throw new ActiveSessionExistsException(
                        "Active impersonation session already exists for impersonator");
            }
            log.warn("ImpersonationSession DB constraint violation (non-active-session): {}", e.getMessage());
            throw new ImpersonationConstraintException(
                    "Session insert failed (constraint): " + e.getMostSpecificCause().getMessage());
        }
    }

    /**
     * Stop an active session — DELETE /current handler delegate.
     *
     * @return true if stopped (was ACTIVE), false if already ended/missing.
     */
    @Transactional
    public boolean stopSession(UUID sessionId, String reason) {
        Instant now = Instant.now();
        int updated = sessionRepository.stopSession(sessionId, now, reason);
        if (updated > 0) {
            log.info("Impersonation session stopped: id={} reason={}", sessionId, reason);
            return true;
        }
        log.debug("Stop session no-op (not active): id={}", sessionId);
        return false;
    }

    /**
     * Get active session for impersonator.
     */
    @Transactional(readOnly = true)
    public Optional<ImpersonationSession> getActiveByImpersonator(Long impersonatorUserId) {
        return sessionRepository.findActiveByImpersonator(impersonatorUserId, Instant.now());
    }

    /**
     * Sweep TTL — scheduled job pattern (auth-service ya da permission-service
     * @Scheduled). Sweeps expired-but-still-ACTIVE rows.
     */
    @Transactional
    public int sweepExpired() {
        int count = sessionRepository.sweepExpiredSessions(Instant.now());
        if (count > 0) {
            log.info("TTL sweep: marked {} session(s) as EXPIRED", count);
        }
        return count;
    }

    /**
     * Request DTO for {@link #startSession(StartSessionRequest)}.
     */
    public record StartSessionRequest(
            Long impersonatorUserId,
            String impersonatorSubject,
            String impersonatorEmail,
            Long targetUserId,
            String targetSubject,
            String targetEmail,
            String issuer,
            String jti,
            String sid,
            String reason,
            Instant expiresAt,
            java.net.InetAddress ipAddress,
            String userAgent,
            java.net.InetAddress clientIpViaXff) {
    }

    /**
     * Single-active-session policy violation — controller 409 mapping.
     */
    public static class ActiveSessionExistsException extends RuntimeException {
        public static final String ERROR_CODE = "ACTIVE_IMPERSONATION_EXISTS";

        public ActiveSessionExistsException(String message) {
            super(message);
        }

        public String errorCode() {
            return ERROR_CODE;
        }
    }

    /**
     * Other DB constraint violations (no_self, expires_after_start, status_check)
     * → 400 BadRequest (not single-active-session 409).
     */
    public static class ImpersonationConstraintException extends RuntimeException {
        public static final String ERROR_CODE = "IMPERSONATION_CONSTRAINT_VIOLATION";

        public ImpersonationConstraintException(String message) {
            super(message);
        }

        public String errorCode() {
            return ERROR_CODE;
        }
    }
}
