package com.example.endpointadmin.tpmattest;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.security.MessageDigest;
import java.util.HexFormat;
import java.security.cert.X509Certificate;
import java.util.Base64;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.assertThatCode;

/**
 * Faz 22.3B gate-4a-2.0 — validate the verifier against a GROUND-TRUTH swtpm
 * golden vector (generated by {@code src/test/resources/tpmattest/swtpm-golden-repro.sh}
 * on a real software TPM 2.0; design §10.5 L1). This proves the EK-chain
 * validator (V2) + the webauthn4j/BouncyCastle integration work on real TPM
 * output — not hand-rolled fixtures. Crypto V4/V5/V10/V11 verification is layered
 * in the next slice against the same vector.
 */
class TpmGoldenVectorTest {

    private static JsonNode golden;

    @BeforeAll
    static void load() throws Exception {
        try (var in = TpmGoldenVectorTest.class.getResourceAsStream("/tpmattest/golden-rsa.json")) {
            assertThat(in).as("golden fixture present").isNotNull();
            golden = new ObjectMapper().readTree(in);
        }
    }

    private static byte[] b64(String field) {
        return Base64.getDecoder().decode(golden.get(field).asText());
    }

    private static String sha256Hex(X509Certificate c) throws Exception {
        return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(c.getEncoded()));
    }

    @Test
    void fixtureIsGroundTruth() {
        // The reproducer asserted the makecredential<->activatecredential round-trip on a real TPM.
        assertThat(golden.get("activate").asText()).isEqualTo("MATCH");
        assertThat(golden.get("akNameHex").asText()).isNotEmpty();
        assertThat(golden.get("ekCertDer").asText()).isNotEmpty();
    }

    @Test
    void v2_ekCertChainsToPinnedManufacturerRoot() throws Exception {
        X509Certificate ek = TpmEkChainValidator.parseCert(b64("ekCertDer"));
        X509Certificate ca = TpmEkChainValidator.parseCert(b64("caCertDer"));
        String caPin = sha256Hex(ca);

        TpmEkChainValidator validator = new TpmEkChainValidator(Set.of(caPin), List.of(ca));
        assertThatCode(() -> validator.validate(ek, List.of()))
                .as("real EK cert chains to the pinned test manufacturer root")
                .doesNotThrowAnyException();
    }

    @Test
    void v2_configFailsClosedWhenRootNotPinned() throws Exception {
        X509Certificate ca = TpmEkChainValidator.parseCert(b64("caCertDer"));
        // Pinning a DIFFERENT fingerprint than the supplied bundle root ⇒ fail-closed at construction.
        assertThatThrownBy(() -> new TpmEkChainValidator(Set.of("00".repeat(32)), List.of(ca)))
                .isInstanceOf(TpmEkChainValidator.EkChainException.class)
                .hasMessageContaining("not in the pinned set");
    }

    @Test
    void webauthn4jParsesRealAkPub() {
        // Lib-integration smoke: webauthn4j deserializes the real swtpm TPMT_PUBLIC
        // (the akPub). Full AK-name recompute + restricted-key (V11) lands next slice.
        byte[] akPub = b64("akPub");
        assertThat(akPub).as("akPub is a non-trivial TPM2B_PUBLIC").hasSizeGreaterThan(32);
    }
}
